name: Add Contributors
on: [push, pull_request]

jobs:
    contrib-readme-job:
        runs-on: ubuntu-latest
        name: A job to automate contrib in readme
        steps:
            - name: Contribute List
              uses: akhilmhdh/contributors-readme-action@v2.0.2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with: 
                  readme_path: CONTRIBUTORS.md
                  commit_message: new contributor added
                  committer_username: github-actions
                  columns_per_row: 5
